variables:
  DOCKER_REGISTRY_HOSTED: "repository.dimas-maryanto.com:8087"
  DOCKER_REGISTRY_PUBLIC: "repository.dimas-maryanto.com:8086"
  IMAGE_NAME: "openjdk8-ffmpeg"
cache:
  paths:
    - .m2/repository

building-image:
  stage: build
  before_script:
    - 'docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD $DOCKER_REGISTRY_HOSTED'
    - 'docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD $DOCKER_REGISTRY_PUBLIC'
  script:
    - 'docker build -t $IMAGE_NAME:$CI_COMMIT_TAG .'
    - 'docker tag $IMAGE_NAME:$CI_COMMIT_TAG $DOCKER_REGISTRY_HOSTED/$IMAGE_NAME:$CI_COMMIT_TAG'
    - 'docker push $DOCKER_REGISTRY_HOSTED/$IMAGE_NAME:$CI_COMMIT_TAG'
  only:
    - /-release$/
